### ISSUE TITLE
Possibly change formatters

### ISSUE THREAD

**Issue by steveoh** [agrc/python#26]
What do you all think about updating this to use black instead of yapf?

https://github.com/psf/black

It seems more like prettier for javascript which we have really come to like.

Would this be a cheese move or do you see some value in using a more active/popular/maybe faster package?

**Comment by stdavis** [comment]
I absolutely love prettier so if this is a step closer to that standard, I'm all for it. It does seem like it's much more active than yapf. Also, switching formatters isn't a huge deal. I'd definitely be up for trying it out.
