### ISSUE TITLE
Transition to pyproject.toml

### ISSUE THREAD

**Issue by jacobdadams** [agrc/python#30]
The current preferred way of controlling python packaging is through a `pyproject.toml` file that can mostly or entirely replace `setup.py`. This is a note to get this on our radar and save progress/knowledge.

This may allow us to stop tracking the version number in source code completely, relying on github tags if we want.

References:
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

**Comment by stdavis** [comment]
This is done.
